apiVersion: apps/v1
kind: Deployment
metadata:
  name: surplex-example
spec:
  selector:
    matchLabels:
      app: example
  replicas: 2
  template:
    metadata:
      labels:
        app: example
        environment: production
    spec:
      containers:
      - name: surplex-example
        image: danielschischkin/surplex-example:latest
        ports:
        - containerPort: 80
        - containerPort: 443
